version: 2.1

orbs:
  docker: circleci/docker@2.8.1

jobs:
  build_publish:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker
      # Publish to ECR
      - run:
          name: Make Deploy Script Executable
          command: chmod +x ./scripts-pipeline/publish.sh
      - run: './scripts-pipeline/publish.sh'

  deploy:
    # circleci_ip_ranges: true # opts the job into the IP ranges feature
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      # - run: ssh -o StrictHostKeyChecking=no -v $EC2_USER@$EC2_INSTANCE_IP "./deploy.sh"
      - checkout
      # Trigger EC2 deployment
      - run:
          name: Make Deploy Script Executable
          command: chmod +x ./scripts-pipeline/deploy.sh
      - run: './scripts-pipeline/deploy.sh'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      # - build_publish:
      #     context: circle-ci  # Apply context to the build_publish job
      #     filters:
      #       branches:
      #         only: 
      #           - main  # Adjust this to your main branch
      - deploy:
          # requires:
          #   - build_publish
          context: aws-ec2  # Apply context to the deploy job
          filters:
            branches:
              only: 
                - main  # Adjust this to your main branch